version: "3.8"

services:
  express-app:
    image: ov3rsiz3/express-app:main
    ports:
      - "3000:3000"
    restart: always

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_CLEANUP=true
    restart: always
